Add validation logic to the secret configuration
adnovum/tenantsecrets pull request #6
Opened 2023-05-22 14:53 UTC by rkrisztian

2023-05-22 15:18 UTC, sandro-h requested changes

2023-05-22 15:18 UTC, sandro-h commented on plugin/src/main/java/com/vary/tenantsecrets/validators/SecretConfigValidator.java
> +                    if (!AT_LEAST_TWO_HEX_DIGITS.matcher(cipher).matches() || cipher.length() % 2 != 0) {
Couldn't we call `KeyProvider.fromFile` to read the cipher the same way the plugin does when looking up a secret, and then convert exceptions to a validation error? It would make this logic simpler and aligned with what the plugin actually does. Downside is we may not be able to give precise validation feedback, but at the moment it's pretty generic, too.

2023-05-22 15:20 UTC, rkrisztian commented on plugin/src/main/java/com/vary/tenantsecrets/validators/SecretConfigValidator.java
> +                    if (!AT_LEAST_TWO_HEX_DIGITS.matcher(cipher).matches() || cipher.length() % 2 != 0) {
Sure, I can give it a try, thanks!

2023-05-23 14:22 UTC, sandro-h approved these changes
Looks good 👍 Thanks for the cleanups as well.

2023-05-23 14:23 UTC, rkrisztian commented on plugin/src/test/java/com/vary/tenantsecrets/validators/SecretConfigValidatorTest.java
> +                Arguments.of("", GIVEN_PATH_IS_NOT_A_FILE)
On a second thought, both paths could be relative to `tempDir`.

2023-05-23 14:50 UTC, merged